databases:
  - name: snike
    user: snike 
    plan: free
    region: ohio

services:
  - type: web
    name: snike 
    plan: free
    region: oregon
    branch: main
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: snike 
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false


